recipes/urls.py
from django.urls import path

from recipes.views import \
    recipe_list, recipe_create_view, recipe_detail, recipe_update_view, recipe_hx_detail, \
    recipe_hx_ingredient_update, recipe_delete, recipe_ingredient_delete, image_upload_view

app_name = 'recipes'

urlpatterns = [
    path('', recipe_list, name='list'),
    path('create/', recipe_create_view, name='create'),

    path('hx/<int:parent_id>/ingredient/<int:id>/', recipe_hx_ingredient_update,
         name='hx-ingredient-update'),
    path('hx/<int:parent_id>/ingredient/', recipe_hx_ingredient_update,
         name='hx-ingredient-create'),
    path('hx/<int:id>/', recipe_hx_detail, name='hx-detail'),

    path('<int:parent_id>/image-upload/', image_upload_view,
         name='image-upload'),
    path('delete/<int:parent_id>/ingredient/<int:id>/', recipe_ingredient_delete,
         name='ingredient-delete'),
    path('<int:id>/delete/', recipe_delete, name='delete'),
    path('<int:id>/edit/', recipe_update_view, name='update'),
    path('<int:id>/', recipe_detail, name='detail'),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import include, path

from search.views import search_view
from trydjango.views import home_page
from accounts.views import login_view, logout_view, register_user
from meals.views import meal_toggle_queue_view

urlpatterns = [
    # custom
    path('', home_page, name='home_page'),
    path('search/', search_view, name='search'),
    path('library/recipes/', include('recipes.urls')),
    path('article/', include('articles.urls')),
    path('meal-toggle/<int:recipe_id>/', meal_toggle_queue_view, name='meal-toggle'),
    # admin
    path('admin/', admin.site.urls),
    # register
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_user, name='register'),
]

recipes/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.db.models import Q

import pint
import pathlib
import uuid

from recipes.utils import number_str_to_float
from recipes.validators import check_valid_value


class RecipeQuerySet(models.QuerySet):
    def search(self, query):
        if query is None or query == '':
            return self.none()
        lookups = (
                Q(name__icontains=query) | Q(description__icontains=query) | Q(directions__icontains=query)
        )
        return self.filter(lookups)


class RecipeManager(models.Manager):
    def get_queryset(self):
        return RecipeQuerySet(self.model, self._db)

    def search(self, query):
        return self.get_queryset().search(query)


class Recipe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=True)
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    created = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    objects = RecipeManager()

    @property
    def title(self):
        return self.name

    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('recipes:delete', kwargs={'id': self.id})

    def get_edit_url(self):
        return reverse('recipes:update', kwargs={'id': self.id})

    def get_hx_url(self):
        return reverse('recipes:hx-detail', kwargs={'id': self.id})

    def get_ingredients_children(self):
        return self.recipeingredient_set.all()


def ingredient_directory_path(instance, filename):
    fpath = pathlib.Path(filename)
    return f'ingredient/uploads/{uuid.uuid1()}{fpath.suffix}'


class RecipeIngredientImage(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    image = models.FileField(upload_to=ingredient_directory_path)


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=True)
    quantity = models.CharField(max_length=50)
    quantity_as_float = models.FloatField(blank=True, null=True)
    unit = models.CharField(max_length=50, validators=[check_valid_value])
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    created = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def get_hx_edit_url(self):
        kwargs = {
            'id': self.id,
            'parent_id': self.recipe.id
        }
        return reverse('recipes:hx-ingredient-update', kwargs=kwargs)

    def get_absolute_url(self):
        return self.recipe.get_absolute_url()

    def get_delete_url(self):
        kwargs = {
            'id': self.id,
            'parent_id': self.recipe.id
        }
        return reverse('recipes:ingredient-delete', kwargs=kwargs)

    def convert_to_system(self, system='mks'):
        if self.quantity_as_float is None:
            return None
        ureg = pint.UnitRegistry(system=system)
        measurement = self.quantity_as_float * ureg[self.unit]
        return measurement

    def as_mks(self):
        measurement = self.convert_to_system(system='mks')
        return measurement.to_base_units()

    def as_imperial(self):
        measurement = self.convert_to_system(system='imperial')
        return measurement.to_base_units()

    def save(self, *args, **kwargs):
        quantity = self.quantity
        quantity_as_float, is_quantity_as_float = number_str_to_float(str(quantity))
        if is_quantity_as_float:
            self.quantity_as_float = quantity_as_float
        else:
            self.quantity_as_float = None
        super().save(*args, **kwargs)

recipes/forms.py
from django import forms

from recipes.models import Recipe, RecipeIngredient, RecipeIngredientImage


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredientImage
        fields = ['image']


class RecipeForm(forms.ModelForm):
    error_css_class = 'error-field'
    required_css_class = 'required-field'
    name = forms.CharField(help_text='This is your help <a href="/contact/">Contact use</a>')
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}))
    directions = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}))

    class Meta:
        model = Recipe
        fields = ['name', 'description', 'directions']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['name'].widget.attrs.update({'class': 'form-control'})
        # self.fields['name'].label = ''
        for field in self.fields:
            add_data = {
                'class': 'form-control',
                'placeholder': f'Recipe {field}',
                'hx-post': '.',
                'hx-trigger': 'keyup change delay:100ms',
                'hx-target': '#recipe-container',
                'hx-swap': "outerHTML"
            }
            self.fields[field].widget.attrs.update(**add_data)


class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = ['name', 'quantity', 'unit']

recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from django.shortcuts import reverse

from recipes.forms import RecipeForm, RecipeIngredientForm, ImageUploadForm
from recipes.models import Recipe, RecipeIngredient


@login_required
def recipe_list(request):
    recipes = Recipe.objects.filter(user=request.user)
    context = {
        'recipes': recipes
    }
    return render(request, 'recipes/list.html', context)


@login_required
def recipe_detail(request, id=None):
    hx_url = reverse("recipes:hx-detail", kwargs={"id": id})
    context = {
        "hx_url": hx_url
    }
    return render(request, "recipes/detail.html", context)


@login_required
def recipe_hx_detail(request, id=None):
    try:
        obj = Recipe.objects.get(id=id, user=request.user)
    except:
        obj = None
    if obj is None:
        return HttpResponse("Not found.")
    context = {
        "object": obj
    }
    return render(request, "recipes/partials/detail.html", context)


@login_required
def recipe_delete(request, id=None):
    try:
        object = Recipe.objects.get(id=id, user=request.user)
    except:
        object = None

    if object is None:
        if request.htmx:
            return HttpResponse('NotFound')
        raise Http404()

    if request.method == 'POST':
        object.delete()
        success_url = reverse('recipes:list')
        if request.htmx:
            header = {
                'HX-Redirect': success_url
            }
            return HttpResponse('Success', headers=header)
        return redirect(success_url)
    context = {
        "object": object
    }
    return render(request, "recipes/delete.html", context)


@login_required
def recipe_ingredient_delete(request, parent_id=None, id=None):
    try:
        object = RecipeIngredient.objects.get(id=id, recipe__id=parent_id)
    except:
        object = None

    if object is None:
        if request.htmx:
            return HttpResponse('NotFound')
        raise Http404()

    obj_htmx = object

    if request.method == 'POST':
        object.delete()
        success_url = reverse('recipes:update', kwargs={'id': parent_id})
        if request.htmx:
            return render(request, "recipes/partials/ingredient-inline-remove.html", {'object': obj_htmx})
        return redirect(success_url)
    context = {
        "object": object
    }
    return render(request, "recipes/delete.html", context)


@login_required
def recipe_create_view(request):
    form = RecipeForm(request.POST or None)
    context = {
        "form": form
    }
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()
        if request.htmx:
            header = {
                'HX-Redirect': obj.get_absolute_url()
            }
            return HttpResponse('Created', headers=header)
        return redirect(obj.get_absolute_url())
    return render(request, "recipes/create_update.html", context)


@login_required
def recipe_update_view(request, id=None):
    obj = get_object_or_404(Recipe, id=id, user=request.user)
    form = RecipeForm(request.POST or None, instance=obj)
    new_ingredient_url = reverse('recipes:hx-ingredient-create', kwargs={'parent_id': obj.id})
    context = {
        "form": form,
        "object": obj,
        "new_ingredient_url": new_ingredient_url
    }
    if form.is_valid():
        form.save()
        context['message'] = 'Data saved.'
    if request.htmx:
        return render(request, "recipes/partials/forms.html", context)
    return render(request, "recipes/create_update.html", context)


@login_required
def recipe_hx_ingredient_update(request, parent_id=None, id=None):
    if not request.htmx:
        return Http404()
    try:
        parent = Recipe.objects.get(id=parent_id, user=request.user)
    except:
        parent = None
    if parent is None:
        return HttpResponse("Not found.")

    instance = None
    if id is not None:
        try:
            instance = RecipeIngredient.objects.get(id=id, recipe=parent)
        except:
            instance = None

    form = RecipeIngredientForm(request.POST or None, instance=instance)
    url = reverse('recipes:hx-ingredient-create', kwargs={'parent_id': parent.id})
    if instance:
        url = instance.get_hx_edit_url()

    context = {
        'url': url,
        'form': form,
        "object": instance
    }
    if form.is_valid():
        new_obj = form.save(commit=False)
        if instance is None:
            new_obj.recipe = parent
        new_obj.save()
        context['object'] = new_obj
        return render(request, 'recipes/partials/ingredient-inline.html', context)
    return render(request, 'recipes/partials/ingredient-form.html', context)


@login_required
def image_upload_view(request, parent_id=None):
    template = 'recipes/image-upload-form.html'
    if request.htmx:
        template = 'recipes/partials/image-form.html'
    try:
        parent_instance = Recipe.objects.get(id=parent_id, user=request.user)
    except:
        parent_instance = None
    if parent_instance is None:
        raise Http404()

    form = ImageUploadForm(request.POST or None, request.FILES or None)
    context = {'form': form}
    if form.is_valid():
        recipe_image = form.save(commit=False)
        recipe_image.recipe = parent_instance
        recipe_image.save()
    return render(request, template, context)

recipes/templates/recipes/create_update.html
{% extends "base.html" %}


{% block content %}

<style>
    .ingredient-form {
        border-bottom: 1px solid black;
    }
    .hidden {
        display: none
    }

</style>

<div class="row" style='margin-top:30px;'>
    <div class="{% if object.id %}col-12 col-md-8 {% else %} col-md-6 mx-auto {% endif %}">
        {% if not object.id %}
        <h1>Object create</h1>
        {%  endif %}
        {% include 'recipes/partials/forms.html' %}
    </div>
    <div class="{% if object.id %}col-12 col-md-4 {% else %} d-none {% endif %}">

        <h3>Ingredients</h3>
        {% for ingredient in object.get_ingredients_children %}
        {% include 'recipes/partials/ingredient-inline.html' with object=ingredient %}
        {% endfor %}
        {% if new_ingredient_url %}
        <div id='ingredient-create'>

        </div>

        <button hx-get="{{ new_ingredient_url }}" hx-trigger='click'
                hx-target='#ingredient-create' hx-swap='beforeend'>Add ingredient
        </button>

        {% endif %}
    </div>

</div>

<script>


    document.addEventListener('click', (event)=>{
        if (event.target.id == 'add-more') {
            add_new_form(event)
        }
    })
    function add_new_form(event) {
        if (event) {
            event.preventDefault()
        }
        const totalNewForms = document.getElementById('id_form-TOTAL_FORMS')
        const currentIngredientForms = document.getElementsByClassName('ingredient-form')
        const currentFormCount = currentIngredientForms.length // + 1
        const formCopyTarget = document.getElementById('ingredient-form-list')
        const copyEmptyFormEl = document.getElementById('empty-form').cloneNode(true)
        copyEmptyFormEl.setAttribute('class', 'ingredient-form')
        copyEmptyFormEl.setAttribute('id', `form-${currentFormCount}`)
        const regex = new RegExp('__prefix__', 'g')
        copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currentFormCount)
        totalNewForms.setAttribute('value', currentFormCount + 1)
        // now add new empty form element to our html form
        formCopyTarget.append(copyEmptyFormEl)
    }




</script>


{% endblock content %}

recipes/templates/recipes/delete.html
{% extends 'base.html' %}


{% block content %}

<form action="." method="POST">
    {% csrf_token %}
    <p>Are you sure to delete this object {{ object.name }} </p>
    <button type="submit">Delete</button>
</form>
{% endblock content %}

recipes/templates/recipes/detail.html
{% extends "base.html" %}


{% block content %}

<div hx-get='{{ hx_url }}' hx-trigger='revealed'>
    <div class="htmx-indicator">Loading...</div>
</div>

{% endblock content %}

recipes/templates/recipes/image-upload-form.html
{% extends 'base.html' %}


{% block content %}


{% include 'recipes/partials/image-form.html' %}

{% endblock content %}

recipes/templates/recipes/list.html
{% extends "base.html" %}

{% block content %}
<h1>My Recipes</h1>
<h3><a href='{% url "recipes:create" %}'>Add Recipe</a></h3>
<hr/>
{% for x in recipes %}
        <div class='mb-3'>
            <a class='lead' href='{{ x.get_absolute_url }}'>{{ x.name }}</a>
            <div hx-get='{% url "meal-toggle" recipe_id=x.id %}' hx-trigger='revealed'></div>
    </div>
    {% endfor %}

{% endblock content %}