articles/urls.py
from django.urls import path

from articles.views import article_search, article_create, article_detail

app_name = 'articles'
urlpatterns = [
    path('', article_search, name='search'),
    path('create/', article_create, name='create'),
    path('<slug:slug>/', article_detail, name='detail'),
]

recipes/urls.py
from django.urls import path

from recipes.views import \
    recipe_list, recipe_create_view, recipe_detail, recipe_update_view, recipe_hx_detail, \
    recipe_hx_ingredient_update, recipe_delete, recipe_ingredient_delete, image_upload_view

app_name = 'recipes'

urlpatterns = [
    path('', recipe_list, name='list'),
    path('create/', recipe_create_view, name='create'),

    path('hx/<int:parent_id>/ingredient/<int:id>/', recipe_hx_ingredient_update,
         name='hx-ingredient-update'),
    path('hx/<int:parent_id>/ingredient/', recipe_hx_ingredient_update,
         name='hx-ingredient-create'),
    path('hx/<int:id>/', recipe_hx_detail, name='hx-detail'),

    path('<int:parent_id>/image-upload/', image_upload_view,
         name='image-upload'),
    path('delete/<int:parent_id>/ingredient/<int:id>/', recipe_ingredient_delete,
         name='ingredient-delete'),
    path('<int:id>/delete/', recipe_delete, name='delete'),
    path('<int:id>/edit/', recipe_update_view, name='update'),
    path('<int:id>/', recipe_detail, name='detail'),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import include, path

from search.views import search_view
from trydjango.views import home_page
from accounts.views import login_view, logout_view, register_user
from meals.views import meal_toggle_queue_view

urlpatterns = [
    # custom
    path('', home_page, name='home_page'),
    path('search/', search_view, name='search'),
    path('library/recipes/', include('recipes.urls')),
    path('article/', include('articles.urls')),
    path('meal-toggle/<int:recipe_id>/', meal_toggle_queue_view, name='meal-toggle'),
    # admin
    path('admin/', admin.site.urls),
    # register
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_user, name='register'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://unpkg.com/htmx.org@1.9.2"></script>

    <link rel="stylesheet" href="{% static 'recipes/htmx.css' %}">

</head>

<body>

{% include 'base/navbar.html' %}


<div class="container">

        {% block content %}

        {% endblock %}

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script>
            document.body.addEventListener("htmx:configRequest", (event)=>{
                event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'
            })

</script>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<br>
<p>{{x}}</p>
<h3>{{article_title}} (id: {{article.id}})</h3>
<hr>
<p>{{article_content}}</p>

<a href="{% url 'articles:create' %}">Article create</a>
<a href="{% url 'articles:detail' slug=article.slug %}">Article detail</a>

{% for article in articles %}
    {% if article.title %}
        <p><a href="{{article.get_absolute_url}}">{{ article.title }}</a></p>
    {% endif %}
{% endfor %}
{% endblock %}